name: toxicity
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_statusbarcolor_ns: ^0.5.0
  image_picker: ^0.8.7+4
  extended_image: ^7.0.2
  lottie: ^2.3.2
  share_plus: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-ExtraBold.ttf
        - asset: assets/font/Inter-SemiBold.ttf
        - asset: assets/font/Inter-Thin.ttf
        - asset: assets/font/Inter-Light.ttf
        - asset: assets/font/Inter-ExtraLight.ttf
